version: "3.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    ports:
    - "9200:9200"
    environment:
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
      xpack.security.enabled: "false"
  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    ports:
    - "5601:5601"
    environment:
      xpack.security.enabled: "false"
  logstash:
    image: docker.elastic.co/logstash/logstash:$ELASTIC_VERSION
    ports:
    - "9600:9600"
    environment:
      PIPELINE_WORKERS: 1
    volumes:
    - ./logstash/:/usr/share/logstash/pipeline/
    - ./log/:/usr/share/logstash/log/
    - ./elasticsearch:/usr/share/logstash/elasticsearch/